name: Get Server Info

concurrency:
  group: "main"
  cancel-in-progress: false
# just manual for now, going to run the action to see how long it takes (and figure out the right interval)
on: [workflow_dispatch]

jobs:
  scan1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 1
      - uses: actions/upload-artifact@v3
        with: 
          name: scan1.json
          path: tmp/scan1.json
  scan2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 2
      - uses: actions/upload-artifact@v3
        with: 
          name: scan2.json
          path: tmp/scan2.json
  cleanup:
    runs-on: ubuntu-latest
    needs: [scan1, scan2]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v3
        with:
          name: scan1.json
          path: tmp/
      - uses: actions/download-artifact@v3
        with:
          name: scan2.json
          path: tmp/
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Cleanup
        run: node clean.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.2
        with:
          default_author: github_actions
          commit: --amend --no-edit
          pull: --rebase --autostash
