name: Get Server Info

concurrency:
  group: "main"
  cancel-in-progress: false

on: [workflow_dispatch, push]

jobs:
  scan1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 1
      - uses: actions/upload-artifact@v3
        with: 
          name: data1.json
          path: tmp/data1.json
  scan2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 2
      - uses: actions/upload-artifact@v3
        with: 
          name: data2.json
          path: tmp/data2.json
  cleanup:
    runs-on: ubuntu-latest
    needs: [scan1, scan2]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v3
        with:
          name: data1.json
          path: tmp/
      - uses: actions/download-artifact@v3
        with:
          name: data2.json
          path: tmp/
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Cleanup
        run: node clean.js
      - name: Commit and push any changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          timestamp=$(date -u)
          git config pull.rebase true
          git pull
          git add -A
          git commit -m "Latest data: ${timestamp}" --amend --no-edit || exit 0
          git push
