name: Get Server Info

concurrency:
  group: "main"
  cancel-in-progress: false
# just manual for now, going to run the action to see how long it takes (and figure out the right interval)
on: [workflow_dispatch]

jobs:
  scan1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 1
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.2
        with:
          default_author: github_actions
          commit: --amend --no-edit
          pull: --rebase --autostash
  scan2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js 2
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.2
        with:
          default_author: github_actions
          commit: --amend --no-edit
          pull: --rebase --autostash
  cleanup:
    runs-on: ubuntu-latest
    needs: [scan1, scan2]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Cleanup
        run: node clean.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.2
        with:
          default_author: github_actions
          commit: --amend --no-edit
          pull: --rebase --autostash
