name: Update Data

concurrency:
  group: "main"
  cancel-in-progress: false

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip 
          python3 -m pip install -r requirements.txt
      - name: Update README
        run: |
          python3 --version
          python3 get_server_info.py 
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

      - name: Commit to the repo
        run: |
          git config user.name "thegu5"
          git config user.email "null"
          git add .
          git commit -m 'Update Servers.json from ip list' || echo
          git push -f origin main
