name: Get Server Info

concurrency:
  group: "main"
  cancel-in-progress: false
# just manual for now, going to run the action to see how long it takes (and figure out the right interval)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Check servers
        run: node index.js
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Get server Info
        
