name: Update Data

concurrency:
  group: "main"
  cancel-in-progress: false

on:
  push: {branches: ["master", "main"]}
  schedule:
    [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip 
          python3 -m pip install -r requirements.txt
      - name: Update README
        run: |
          python3 --version
          python3 update_data.py 
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

      - name: Commit to the repo
        run: |
          git config user.name "Declipsonator"
          git config user.email "null"
          git add .
          git commit -m 'Update README' || echo
          git push -f origin main
